apiVersion: v1
kind: Service
metadata:
  name: {{ include "enmasse.fullname" . }}-api-server
  labels:
{{ include "enmasse.labels" . | indent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "enmasse.fullname" . }}-api-server-cert
{{ toYaml .Values.apiServer.service.annotations | nindent 4 }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: health
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "enmasse.fullname" . }}-api-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
